### ISSUE TITLE
trouble to use this library with Adafruit_cc3000 library

### ISSUE THREAD

**Issue by taher143** [leg0/Arduino-Websocket#12]
I am having trouble with testing the web-socket client with cc3000 arduino. I have taken reference files from brandenhall/Arduino-Websocket repository. I am not able to connect to the server through client. getting bad request 404 error or time out error each time. 
Please explain me the way to test it locally.
here is my code which I have used for arduino client.

#include <Base64.h>
#include <global.h>
#include <MD5.h>
#include <sha1.h>
#include <WebSocketClient.h>

/*************************************************** 
  This is an example for the Adafruit CC3000 Wifi Breakout & Shield

  Designed specifically to work with the Adafruit WiFi products:
  ----> https://www.adafruit.com/products/1469

  Adafruit invests time and resources providing this open source code, 
  please support Adafruit and open-source hardware by purchasing 
  products from Adafruit!

  Written by Limor Fried & Kevin Townsend for Adafruit Industries.  
  BSD license, all text above must be included in any redistribution
 ****************************************************/
 
 /*
This example does a test of the TCP client capability:
  * Initialization
  * Optional: SSID scan
  * AP connection
  * DHCP printout
  * DNS lookup
  * Optional: Ping
  * Connect to website and print out webpage contents
  * Disconnect
SmartConfig is still beta and kind of works but is not fully vetted!
It might not work on all networks!
*/
#include <Adafruit_CC3000.h>
#include <ccspi.h>
#include <SPI.h>
#include <string.h>
#include "utility/debug.h"
#define MAX_FRAME_LENGTH 64

// Define how many callback functions you have. Default is 1.
#define CALLBACK_FUNCTIONS 1

#include <WebSocketClient.h>

WebSocketClient webSocketClient;
// These are the interrupt and control pins
#define ADAFRUIT_CC3000_IRQ   3  // MUST be an interrupt pin!
// These can be any two pins
#define ADAFRUIT_CC3000_VBAT  5
#define ADAFRUIT_CC3000_CS    10
// Use hardware SPI for the remaining pins
// On an UNO, SCK = 13, MISO = 12, and MOSI = 11
Adafruit_CC3000 cc3000 = Adafruit_CC3000(ADAFRUIT_CC3000_CS, ADAFRUIT_CC3000_IRQ, ADAFRUIT_CC3000_VBAT,
                                         SPI_CLOCK_DIVIDER); // you can change this clock speed

#define WLAN_SSID       "UNSTOPPABLE"           // cannot be longer than 32 characters!
#define WLAN_PASS       "8878333344"
// Security can be WLAN_SEC_UNSEC, WLAN_SEC_WEP, WLAN_SEC_WPA or WLAN_SEC_WPA2
#define WLAN_SECURITY   WLAN_SEC_WPA2

#define IDLE_TIMEOUT_MS  3000      // Amount of time to wait (in milliseconds) with no data 
                                   // received before closing the connection.  If you know the server
                                   // you're accessing is quick to respond, you can reduce this value.

// What page to grab!
#define WEBSITE      "www.pravelsolutions.com"
#define WEBPAGE      "/aspero/activation.php?name=\"Aspero_1\"&serial=0000000001"

/**************************************************************************/
/*!
    @brief  Sets up the HW and the CC3000 module (called automatically
            on startup)
*/
/**************************************************************************/

uint32_t ip;

void setup(void)
{
  String data;
  Serial.begin(115200);
  Serial.println(F("Hello, CC3000!\n")); 

  Serial.print("Free RAM: "); Serial.println(getFreeRam(), DEC);
  
  /* Initialise the module */
  Serial.println(F("\nInitializing..."));
  if (!cc3000.begin())
  {
    Serial.println(F("Couldn't begin()! Check your wiring?"));
    while(1);
  }
  
  // Optional SSID scan
  // listSSIDResults();
  
  Serial.print(F("\nAttempting to connect to ")); Serial.println(WLAN_SSID);
  if (!cc3000.connectToAP(WLAN_SSID, WLAN_PASS, WLAN_SECURITY)) {
    Serial.println(F("Failed!"));
    while(1);
  }
   
  Serial.println(F("Connected!"));
  
  /* Wait for DHCP to complete */
  Serial.println(F("Request DHCP"));
  while (!cc3000.checkDHCP())
  {
    delay(100); // ToDo: Insert a DHCP timeout!
  }  

  /* Display the IP address DNS, Gateway, etc. */  
  while (! displayConnectionDetails()) {
    delay(1000);
  }

  ip = 0;
  // Try looking up the website's IP address
  Serial.print(WEBSITE); Serial.print(F(" -> "));
  while (ip == 0) {
    if (! cc3000.getHostByName(WEBSITE, &ip)) {
      Serial.println(F("Couldn't resolve!"));
    }
    delay(500);
  }

  cc3000.printIPdotsRev(ip);
  
  // Optional: Do a ping test on the website
  /*
  Serial.print(F("\n\rPinging ")); cc3000.printIPdotsRev(ip); Serial.print("...");  
  replies = cc3000.ping(ip, 5);
  Serial.print(replies); Serial.println(F(" replies"));
  */  

  /* Try connecting to the website.
     Note: HTTP/1.1 protocol is used to keep the server from closing the connection before all data is read.
  */
  Adafruit_CC3000_Client www = cc3000.connectTCP(ip, 80);
  if (www.connected()) {
    Serial.println(F("Connected."));
  /*  www.fastrprint(F("GET "));
    www.fastrprint(WEBPAGE);
    www.fastrprint(F(" HTTP/1.1\r\n"));
    www.fastrprint(F("Host: ")); www.fastrprint(WEBSITE); www.fastrprint(F("\r\n"));
    www.fastrprint(F("\r\n"));
    www.println();*/
  } else {
    Serial.println(F("Connection failed"));    
    return;
  }

  Serial.println(F("-------------------------------------"));
  
  /* Read data until either the connection is closed, or the idle timeout is reached. */ 
/*  unsigned long lastRead = millis();
  while (www.connected() && (millis() - lastRead < IDLE_TIMEOUT_MS)) {
    while (www.available()) {
      char c = www.read();
      Serial.print(c);
      lastRead = millis();
    }
  }
  www.close();
  Serial.println(F("-------------------------------------"));*/
  
  /* You need to make sure to clean up after yourself or the CC3000 can freak out */
  /* the next time your try to connect ... */
//  Serial.println(F("\n\nDisconnecting"));
//  cc3000.disconnect();
// Handshake with the server
  webSocketClient.path = "/";
  webSocketClient.host = "www.pravelsolutions.com";
  
  if (webSocketClient.handshake(www)) {
    Serial.println("Handshake successful");
  } else {
    Serial.println("Handshake failed.");
    while(1) {
      // Hang on failure
    }  
  }
  
  if (www.connected()) {
    
 /*   data = webSocketClient.getData();

    if (data.length() > 0) {
      Serial.print("Received data: ");
      Serial.println(data);
    }*/
    
    // capture the value of analog 1, send it along
    pinMode(1, INPUT);
    data = String(analogRead(1));
    
    webSocketClient.sendData(data);
    
  } else {
    
    Serial.println("Client disconnected.");
    while (1) {
      // Hang on disconnect.
    }
  }
  
  // wait to fully let the client disconnect
  delay(3000);
  
}

void loop(void)
{
// delay(1000);
 
  
}

/**************************************************************************/
/*!
    @brief  Begins an SSID scan and prints out all the visible networks
*/
/**************************************************************************/

void listSSIDResults(void)
{
  uint32_t index;
  uint8_t valid, rssi, sec;
  char ssidname[33]; 

  if (!cc3000.startSSIDscan(&index)) {
    Serial.println(F("SSID scan failed!"));
    return;
  }

  Serial.print(F("Networks found: ")); Serial.println(index);
  Serial.println(F("================================================"));

  while (index) {
    index--;

    valid = cc3000.getNextSSID(&rssi, &sec, ssidname);
    
    Serial.print(F("SSID Name    : ")); Serial.print(ssidname);
    Serial.println();
    Serial.print(F("RSSI         : "));
    Serial.println(rssi);
    Serial.print(F("Security Mode: "));
    Serial.println(sec);
    Serial.println();
  }
  Serial.println(F("================================================"));

  cc3000.stopSSIDscan();
}

/**************************************************************************/
/*!
    @brief  Tries to read the IP address and other connection details
*/
/**************************************************************************/
bool displayConnectionDetails(void)
{
  uint32_t ipAddress, netmask, gateway, dhcpserv, dnsserv;
  
  if(!cc3000.getIPAddress(&ipAddress, &netmask, &gateway, &dhcpserv, &dnsserv))
  {
    Serial.println(F("Unable to retrieve the IP Address!\r\n"));
    return false;
  }
  else
  {
    Serial.print(F("\nIP Addr: ")); cc3000.printIPdotsRev(ipAddress);
    Serial.print(F("\nNetmask: ")); cc3000.printIPdotsRev(netmask);
    Serial.print(F("\nGateway: ")); cc3000.printIPdotsRev(gateway);
    Serial.print(F("\nDHCPsrv: ")); cc3000.printIPdotsRev(dhcpserv);
    Serial.print(F("\nDNSserv: ")); cc3000.printIPdotsRev(dnsserv);
    Serial.println();
    return true;
  }
}

Here is a server code which i have used:
#!/php -q
<?php  /*  >php -q server.php  */

error_reporting(E_ALL);
set_time_limit(0);
ob_implicit_flush();

$master  = WebSocket("localhost",12345);
$sockets = array($master);
$users   = array();
$debug   = false;

while(true){
  $changed = $sockets;
  socket_select($changed,$write=NULL,$except=NULL,NULL);
  foreach($changed as $socket){
    if($socket==$master){
      $client=socket_accept($master);
      if($client<0){ console("socket_accept() failed"); continue; }
      else{ connect($client); }
    }
    else{
      $bytes = @socket_recv($socket,$buffer,2048,0);
      if($bytes==0){ disconnect($socket); }
      else{
        $user = getuserbysocket($socket);
        if(!$user->handshake){ dohandshake($user,$buffer); }
        else{ process($user,$buffer); }
      }
    }
  }
}

//---------------------------------------------------------------
function process($user,$msg){
  $action = unwrap($msg);
  say("< ".$action);
  switch($action){
    case "hello" : send($user->socket,"hello human");                       break;
    case "hi"    : send($user->socket,"zup human");                         break;
    case "name"  : send($user->socket,"my name is Multivac, silly I know"); break;
    case "age"   : send($user->socket,"I am older than time itself");       break;
    case "date"  : send($user->socket,"today is ".date("Y.m.d"));           break;
    case "time"  : send($user->socket,"server time is ".date("H:i:s"));     break;
    case "thanks": send($user->socket,"you're welcome");                    break;
    case "bye"   : send($user->socket,"bye");                               break;
    default      : send($user->socket,$action." not understood");           break;
  }
}

function send($client,$msg){
  say("> ".$msg);
  $msg = wrap($msg);
  socket_write($client,$msg,strlen($msg));
}

function WebSocket($address,$port){
  $master=socket_create(AF_INET, SOCK_STREAM, SOL_TCP)     or die("socket_create() failed");
  socket_set_option($master, SOL_SOCKET, SO_REUSEADDR, 1)  or die("socket_option() failed");
  socket_bind($master, $address, $port)                    or die("socket_bind() failed");
  socket_listen($master,20)                                or die("socket_listen() failed");
  echo "Server Started : ".date('Y-m-d H:i:s')."\n";
  echo "Master socket  : ".$master."\n";
  echo "Listening on   : ".$address." port ".$port."\n\n";
  return $master;
}

function connect($socket){
  global $sockets,$users;
  $user = new User();
  $user->id = uniqid();
  $user->socket = $socket;
  array_push($users,$user);
  array_push($sockets,$socket);
  console($socket." CONNECTED!");
}

function disconnect($socket){
  global $sockets,$users;
  $found=null;
  $n=count($users);
  for($i=0;$i<$n;$i++){
    if($users[$i]->socket==$socket){ $found=$i; break; }
  }
  if(!is_null($found)){ array_splice($users,$found,1); }
  $index = array_search($socket,$sockets);
  socket_close($socket);
  console($socket." DISCONNECTED!");
  if($index>=0){ array_splice($sockets,$index,1); }
}

function dohandshake($user,$buffer){
  console("\nRequesting handshake...");
  console($buffer);
  list($resource,$host,$origin,$strkey1,$strkey2,$data) = getheaders($buffer);
  console("Handshaking...");

  $pattern = '/[^\d]*/';
  $replacement = '';
  $numkey1 = preg_replace($pattern, $replacement, $strkey1);
  $numkey2 = preg_replace($pattern, $replacement, $strkey2);

  $pattern = '/[^ ]*/';
  $replacement = '';
  $spaces1 = strlen(preg_replace($pattern, $replacement, $strkey1));
  $spaces2 = strlen(preg_replace($pattern, $replacement, $strkey2));

  if ($spaces1 == 0 || $spaces2 == 0 || $numkey1 % $spaces1 != 0 || $numkey2 % $spaces2 != 0) {
﻿  socket_close($user->socket);
﻿  console('failed');
﻿  return false;
  }

  $ctx = hash_init('md5');
  hash_update($ctx, pack("N", $numkey1/$spaces1));
  hash_update($ctx, pack("N", $numkey2/$spaces2));
  hash_update($ctx, $data);
  $hash_data = hash_final($ctx,true);

  $upgrade  = "HTTP/1.1 101 WebSocket Protocol Handshake\r\n" .
              "Upgrade: WebSocket\r\n" .
              "Connection: Upgrade\r\n" .
              "Sec-WebSocket-Origin: " . $origin . "\r\n" .
              "Sec-WebSocket-Location: ws://" . $host . $resource . "\r\n" .
              "\r\n" .
              $hash_data;

  socket_write($user->socket,$upgrade.chr(0),strlen($upgrade.chr(0)));
  $user->handshake=true;
  console($upgrade);
  console("Done handshaking...");
  return true;
}

function getheaders($req){
  $r=$h=$o=null;
  if(preg_match("/GET (.*) HTTP/"   ,$req,$match)){ $r=$match[1]; }
  if(preg_match("/Host: (.*)\r\n/"  ,$req,$match)){ $h=$match[1]; }
  if(preg_match("/Origin: (.*)\r\n/",$req,$match)){ $o=$match[1]; }
  if(preg_match("/Sec-WebSocket-Key2: (.*)\r\n/",$req,$match)){ $key2=$match[1]; }
  if(preg_match("/Sec-WebSocket-Key1: (.*)\r\n/",$req,$match)){ $key1=$match[1]; }
  if(preg_match("/\r\n(.*?)\$/",$req,$match)){ $data=$match[1]; }
  return array($r,$h,$o,$key1,$key2,$data);
}

function getuserbysocket($socket){
  global $users;
  $found=null;
  foreach($users as $user){
    if($user->socket==$socket){ $found=$user; break; }
  }
  return $found;
}

function     say($msg=""){ echo $msg."\n"; }
function    wrap($msg=""){ return chr(0).$msg.chr(255); }
function  unwrap($msg=""){ return substr($msg,1,strlen($msg)-2); }
function console($msg=""){ global $debug; if($debug){ echo $msg."\n"; } }

class User{
  var $id;
  var $socket;
  var $handshake;
}

?>

Also I am not able to find getdata() function from WebsocketClient.cpp fro which I was getting error.

**Comment by leg0** [comment]
Try connecting to ws://echo.websocket.org.

**Comment by taher143** [comment]
connected the websocket client to websocket.org got following response:

Hello, CC3000!

Free RAM: 534

Initializing...

Attempting to connect to UNSTOPPABLE
Connected!
Request DHCP

IP Addr: 192.168.1.4
Netmask: 255.255.255.0
Gateway: 192.168.1.1
DHCPsrv: 192.168.1.1
DNSserv: 192.168.1.1
www.websocket.org -> Errno: 1
192.168.1.1Connected.
-------------------------------------
Client connected
Sending websocket upgrade headers
Analyzing response headers
Waiting...
Got Header: HTTP/1.1 200 OK
Got Header: Content-Type: text/html
Got Header: Date: Sat, 01 Jan 2000 00:00:22 GMT
Got Header: Pragma: no-cache
Got Header: Expires: Thu, 26 Oct 1995 00:00:00 GMT
Got Header: Transfer-Encoding: chunked
Got Header: Server: RomPager/4.07 UPnP/1.0
Got Header: EXT:
Got Header: 
Got Header: 616
Got Header: <html>
Got Header: <head>
Got Header: iso-8859-1">
Got Header: <script language="JavaScript">
Got Header: </script>
Got Header: </head><body topmargin="0" leftmargin="0">
Got Header: <tr>
Got Header: <tr>
Got Header: <font size="+1">
Got Header: ADSL Router</font>
Got Header: <tr>
Got Header: <font color="#FFFFFF" size="+1">
Got Header: Devic Status</font>
Got Header: <tr>
Got Header: <tr>
Got Header: <td bgcolor="#000066">
Got Header: <div align=right>
Got Header: </div></td></tr></table>
Got Header: </body></html>
Got Header: 0
Got Header: 

it hangs afterwards.
does it means that client is working ? or not?

**Comment by taher143** [comment]
connected the websocket client to websocket.org got following response:

Hello, CC3000!

Free RAM: 534

Initializing...

Attempting to connect to UNSTOPPABLE
Connected!
Request DHCP

IP Addr: 192.168.1.4
Netmask: 255.255.255.0
Gateway: 192.168.1.1
DHCPsrv: 192.168.1.1
DNSserv: 192.168.1.1
www.websocket.org -> Errno: 1
192.168.1.1Connected.
-------------------------------------
Client connected
Sending websocket upgrade headers
Analyzing response headers
Waiting...
Got Header: HTTP/1.1 200 OK
Got Header: Content-Type: text/html
Got Header: Date: Sat, 01 Jan 2000 00:00:22 GMT
Got Header: Pragma: no-cache
Got Header: Expires: Thu, 26 Oct 1995 00:00:00 GMT
Got Header: Transfer-Encoding: chunked
Got Header: Server: RomPager/4.07 UPnP/1.0
Got Header: EXT:
Got Header: 
Got Header: 616
Got Header: <html>
Got Header: <head>
Got Header: iso-8859-1">
Got Header: <script language="JavaScript">
Got Header: </script>
Got Header: </head><body topmargin="0" leftmargin="0">
Got Header: <tr>
Got Header: <tr>
Got Header: <font size="+1">
Got Header: ADSL Router</font>
Got Header: <tr>
Got Header: <font color="#FFFFFF" size="+1">
Got Header: Devic Status</font>
Got Header: <tr>
Got Header: <tr>
Got Header: <td bgcolor="#000066">
Got Header: <div align=right>
Got Header: </div></td></tr></table>
Got Header: </body></html>
Got Header: 0
Got Header: 

it hangs afterwards.
does it means that client is working ? or not?

**Comment by taher143** [comment]
some times it just hangs on the: 
Sending websocket upgrade headers
Analyzing response headers

what would be the reason?

**Comment by leg0** [comment]
It doesn't look like you're connecting to a websocket. Have you tried to connect to the this websocket: ws://echo.websocket.org ?

Please, try and format the code and logs using markdown syntax? It looks like some of your logs and code are hidden or missing.

**Comment by taher143** [comment]
I am not able to get connect to eho.websocket.org. Arduino hangs after sending upgrade header,
please show me the way to test my client.

Hello, CC3000!

Free RAM: 563

Initializing...

Attempting to connect to UNSTOPPABLE
Connected!
Request DHCP

IP Addr: 192.168.1.3
Netmask: 255.255.255.0
Gateway: 192.168.1.1
DHCPsrv: 192.168.1.1
DNSserv: 192.168.1.1
echo.websocket.org -> 174.129.224.73-------------------------------------
Client connected
Sending websocket upgrade headers
Analyzing response headers

**Comment by leg0** [comment]
Here are some things you can try:
* use a debugger
* put some logging statements in places you suspect the problem to be
* use a network monitoring tool to see what data is being sent/received.

**Comment by taher143** [comment]
Hello sir,
I am trying to connect to echo.websocket.org. I have added some debug serial print to monitor what happening in code.
Here what I am getting when trying to connect to echo.websocket.org:


echo.websocket.org -> Errno: 1
174.129.224.73-------------------------------------
Client connected
Sending websocket upgrade headers
Analyzing response headers
client not connected
client not available

It seems disconnected from the websocket.org after sending the upgrade headers. I ma confused here. Please look at this and reply me.
eagerly waiting for your reply with good hope

**Comment by leg0** [comment]
Look at the HTTP request and response and see if they're what you expect. For more info about what you should expect to see in request and response can be found form this document: https://tools.ietf.org/html/rfc6455

Is the client connected to actual websocket endpoint bebore you perform clientHandshake()?
Are the host and path passed to clientHandshake() correct? In case of ws://echo.websocket.org/ it should be like this:

    // omitted error handling
    client.connect("174.129.224.73", 80); 
    websocket::clientHandshake(client, "echo.websocket.org", "/");

**Comment by taher143** [comment]
Hi
Thanks for reply. The request which I am sending is correct as per https://tools.ietf.org/html/rfc6455.
client first get connected but after sending the upgrade header client disconnected and become unavailable. so nothing is received from the echo.websocket.org. i have tried www.google.com. it is at least giving be http 400 bad request error. but with echo.websocket.org nothing happens.
here is the arduino code which i am using to connect to the client.

````python
// Handshake with the server
webSocketClient.path = "/";
webSocketClient.host = "echo.websocket.org";
if (webSocketClient.handshake(www)) {
    Serial.println("Handshake successful");
  } 
  else {
    Serial.println("Handshake failed.");
    while(1) {
      // Hang on failure
    }  
  }
````
here is how i am sending the headers:
````python
    socket_client->print(F("GET "));
    socket_client->print(path);
    socket_client->print(F(" HTTP/1.1\r\n"));
    socket_client->print(F("Upgrade: websocket\r\n"));
    socket_client->print(F("Connection: Upgrade\r\n"));
    socket_client->print(F("Host: "));
    socket_client->print(host);
    socket_client->print(CRLF); 
    socket_client->print(F("Sec-WebSocket-Key: "));
    socket_client->print(key);
    socket_client->print(CRLF);
    socket_client->print(F("Sec-WebSocket-Protocol: "));
    socket_client->print(protocol);
    socket_client->print(CRLF);
    socket_client->print(F("Sec-WebSocket-Version: 13\r\n"));
    socket_client->print(CRLF);
````
please suggest me any other debug technique so i can fix this issue. Any little help is highly appreciable sir

**Comment by leg0** [comment]
So, you're not using the library? I think we can close this discussion now.

**Comment by taher143** [comment]
Hello sir, I know its not right to ask it here because it is not related to this library. But I need your help this time so that's why I'm asking here.Please look at this[http://arduino.stackexchange.com/questions/7951/arduino-cc3000-websocket-client/8024#8024] thread and help me out . I will be grateful to you for this.
